### ISSUE TITLE
Error after pressing add button in service details screen

### ISSUE THREAD

**Issue by pedbermar** [eclipse-opensmartclide/smartclide-ide-front-end#53] opened 2023-01-11 12:49 UTC
A pop up show me the following error: Error during GitLab repository creation

![Screenshot 2023-01-11 at 13 45 28](https://user-images.githubusercontent.com/2395216/211810512-d986abbe-19e8-4181-8a67-86c665137274.png)

![Screenshot 2023-01-11 at 13 45 39](https://user-images.githubusercontent.com/2395216/211810407-0280e2fd-77bb-4f03-ad53-d2c07501ecff.png)

Thank you in advance!

**Comment by goncalorolo** [comment] 2023-01-11 14:23
@pedbermar, do you have a space at the end of the service name?

**Comment by pedbermar** [comment] 2023-01-11 20:51
@goncalorolo, yes, but same problem without space

**Comment by goncalorolo** [comment] 2023-01-12 11:56
@nikosnikolaidis, do you have any idea about why this is happening?

**Comment by pedbermar** [comment] 2023-01-13 09:56
@goncalorolo any update on this? Thank you

**Comment by goncalorolo** [comment] 2023-01-13 10:31
> @goncalorolo any update on this? Thank you

I still have not managed to replicate the issue. For me, the service creation is working well.

**Comment by schlotze** [comment] 2023-01-16 11:31
We tried it out with the following result:

- It is working with the gitlab URL: [https://gitlab.dev.smartclide.eu/](https://gitlab.dev.smartclide.eu/)
- It is not working with our organisations gitlab URL (where we have some custom settings)

@pedbermar Could you please check with the gitlab: gitlab.dev.smartclide.eu

**Comment by goncalorolo** [comment] 2023-01-16 11:35
I have been in contact with @pedbermar this morning to solve this issue. He ended up being able to create a service using the frontend in Firefox but not in Chrome (both using https://gitlab.com).

**Comment by deanone** [comment] 2023-01-24 10:22
Is this resolved? Can we close it? @pedbermar @goncalorolo ?

**Comment by goncalorolo** [comment] 2023-01-24 10:27
No changes were made in the code. @pedbermar, started using Firefox to test instead since that browser seemed to work for him. I was not able to reproduce the error at all. But I can think we can close it for now.

**Closed by goncalorolo** 2023-01-24 10:27 UTC
